version: '3.1'
#create network interface
networks:
  FLp2p:
    name: FLp2p
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
#init server
  parent_cart:
    image: parent_cart
    deploy:
      replicas: 10
    build:
      context:  ./
      dockerfile:  Dockerfile.parent
    stdin_open: true
    tty: true
    networks:
      FLp2p:
    restart: on-failure:3
    ports:
      - "5001-5010:5001"