version: '3.1'
#create network interface
services:
#init cart
  child_cart:
    image: child_cart
    deploy:
      replicas: 1
    build:
      context:  ./child_cart
      dockerfile:  Dockerfile
    stdin_open: true
    tty: true
    restart: on-failure:3
