version: '3.1'
#create network interface
networks:
  FLp2p:
    name: FLp2p
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
#parent carts
  parent_cart:
    image: parent_cart
    deploy:
      replicas: 1
    build:
      context:  ./
      dockerfile:  Dockerfile.parent
    stdin_open: true
    tty: true
    networks:
      FLp2p:
    restart: on-failure:3
    ports:
      - "1800-1900:80"
#child cart cart
  child_cart:
    image: child_cart
    deploy:
      replicas: 5
    build:
      context:  ./
      dockerfile:  Dockerfile.child
    stdin_open: true
    tty: true
    networks:
      FLp2p:
    restart: on-failure:3
    ports:
      - "2800-2900:80"

