version: '3.1'
#create network interface
services:
#init cart
  child_cart:
    image: child_cart
    deploy:
      replicas: 1
    build:
      context:  ./
      dockerfile:  Dockerfile.child
    stdin_open: true
    tty: true
    restart: on-failure:3
    ports:
      - "5001:5001"
