version: '3.1'
services:
#init server
  parent_cart:
    image: parent_cart
    deploy:
      replicas: 1
    build:
      context:  ./
      dockerfile:  Dockerfile.parent
    stdin_open: true
    tty: true
    restart: on-failure:3
    ports:
      - "3000:80"
      - "5001:5001"
      - "5000:5000"
      - "8000:8000"
      - "9000:9000"
      - "4000:4000"