name: Build release packages

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - name: Install Node dependencies
        run: cd web_app && yarn install

      - name: Build project with Yarn
        run: cd web_app && yarn build

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create Child cart package
        run: pyinstaller --onefile --add-data "web_app/dist:web_app/dist" --name CHILD_CART_V1.exe C_main.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            This is the first release of Child Cart.
          draft: false
          prerelease: false

      - name: Upload Executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./CHILD_CART_V1.exe
          asset_name: CHILD_CART_V1.exe
          asset_content_type: application/octet-stream