name: Build release packages

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - name: Install Node dependencies
        run: cd web_app && yarn install

      - name: Build project with Yarn
        run: cd web_app && yarn build

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create Child cart package
        run: pyinstaller --onefile --add-data "web_app/dist:web_app/dist" --name CHILD_CART_LINUX C_main.py


      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v3.2.0
          release_name: Release v3.2.0

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist
          asset_name: CHILD_CART_LINUX
          asset_content_type: application/octet-stream
