name: Build release packages

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - name: Change working directory to web_app
        run: cd web_app

      - name: List contents of web_app directory
        run: ls

      - name: Install Node dependencies
        run: yarn install

      - name: Build project with Yarn
        run: yarn build

      - name: Return to root directory
        run: cd ..

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
